using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
    Rigidbody2D rbody;      //Rigidbody2Dï¿½^ï¿½Ì•Ïï¿½
    float axisH = 0.0f;     //ï¿½ï¿½ï¿½ï¿½
    public float speed = 3.0f;  //ï¿½Ú“ï¿½ï¿½ï¿½ï¿½x

    bool isJump = false;
    public float jump = 9.0f;       //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½
    public LayerMask groundLayer;   //ï¿½ï¿½ï¿½nï¿½Å‚ï¿½ï¿½éƒŒï¿½Cï¿½ï¿½ï¿½[
    bool goJump = false;            //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Jï¿½nï¿½tï¿½ï¿½ï¿½O
    bool onGround = false;          //ï¿½nï¿½Ê‚É—ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½O

    //ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Î‰ï¿½
    Animator animator;//ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½^ï¿½[
    public string stopAnime = "PlayerStop";
    public string moveAnime = "PlayerMove";
    public string jumpAnime = "PlayerJump";
    public string goalAnime = "PlayerGoal";
    public string deadAnime = "PlayerOver";

    string nowAnime = "";
    string oldAnime = "";

    public static string gameState = "playing";//ï¿½Qï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½

    public int score = 0;


    // Start is called before the first frame update
    void Start()
    {
        rbody = this.GetComponent<Rigidbody2D>();   //Rigidbody2Dï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
        animator = GetComponent<Animator>();        //Animatorï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
        nowAnime = stopAnime;
        oldAnime = stopAnime;
        gameState = "playing";//ï¿½Qï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
    }

    // Update is called once per frame
    void Update()
    {

        if(gameState != "playing")
        {
            return;
        }

        axisH = Input.GetAxisRaw("Horizontal");    //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì“ï¿½ï¿½Í‚ï¿½`ï¿½Fï¿½bï¿½Nï¿½ï¿½ï¿½ï¿½

        if (axisH > 0.0f)
        {
            Debug.Log("ï¿½Eï¿½Ú“ï¿½");
            transform.localScale = new Vector2(1, 1);
        }
        else if (axisH < 0.0f)
        {
            Debug.Log("ï¿½ï¿½ï¿½Ú“ï¿½");
            transform.localScale = new Vector2(-1, 1);
        }

        //ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        if (JumpCount <= 2&&Input.GetButtonDown("Jump"))
        {
            isJump = true; 
        }

    }

    void OnCollisionEnter2D(Collision collision)
    {
        if(collision.gameObject.tag=="Ground")
        {
            JumpCount = 0;
        }
    }

    void FixedUpdate()
    {

        if(isJump)
        {
            GetComponent<Rigidbody2D>().velocity = Vector2.zero;
            GetComponent<Rigidbody2D>().AddForce(Vector2.up * force);
            jumpCount++;
            isJump = false;
        }

        if(gameState!="playing")
        {
            return ;
        }

        //ï¿½nï¿½ã”»ï¿½ï¿½
        onGround = Physics2D.Linecast(transform.position,
        transform.position - (transform.up * 0.1f), groundLayer);

        if (onGround || axisH != 0)//ï¿½nï¿½Ê‚Ìï¿½orï¿½ï¿½ï¿½xï¿½ï¿½0ï¿½Å‚È‚ï¿½
        {
            rbody.velocity = new Vector2(speed * axisH, rbody.velocity.y);  //ï¿½ï¿½ï¿½xï¿½ï¿½Xï¿½Vï¿½ï¿½ï¿½ï¿½
        }
        if (onGround && goJump)
        {
            //ï¿½nï¿½Ê‚Ìï¿½ÅƒWï¿½ï¿½ï¿½ï¿½ï¿½vï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½
            //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            Debug.Log("ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½I");
            Vector2 jumpPw = new Vector2(0, jump);
            rbody.AddForce(jumpPw, ForceMode2D.Impulse);
            goJump = false;//ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½tï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½ï¿½ë‚·
        }

        if(onGround)
        {
            //ï¿½nï¿½Ê‚Ìï¿½
            if(axisH==0)
            {
                nowAnime = stopAnime;//ï¿½ï¿½~ï¿½ï¿½
            }
            else
            {
                nowAnime = moveAnime;//ï¿½Ú“ï¿½ï¿½ï¿½
            }
        }
        else
        {
            //ï¿½ï¿½
            nowAnime = jumpAnime;
        }
        if(nowAnime!=oldAnime)
        {
            oldAnime = nowAnime;
            animator.Play(nowAnime);//ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Äï¿½
        }
    }

    //ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½v
    public void Jump()
    {
        goJump = true;//ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½tï¿½ï¿½ï¿½Oï¿½ğ—§‚Ä‚ï¿½
        Debug.Log("ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½I");
    }
    //ï¿½ÚGï¿½Jï¿½n
    void OnTriggerEnter2D(Collider2D collision)
    {
        if(collision.gameObject.tag=="Goal")
        {
            Goal();//ï¿½Sï¿½[ï¿½ï¿½
        }
        else if(collision.gameObject.tag=="Dead")
        {
            GameOver();//ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½[ï¿½oï¿½[ 
        }

        else if (collision.gameObject.tag == "ScoreItem")
        {
            ItemData item = collision.gameObject.GetComponent<ItemData>();
            score= item.value;

            Destroy(collision.gameObject);
        }
    }


    //ï¿½Sï¿½[ï¿½ï¿½
    public void Goal()
    {
        animator.Play(goalAnime);

        gameState = "gameclear";
        GameStop();
    }

    //ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½[ï¿½oï¿½[
    public void GameOver()
    {
        animator.Play(deadAnime);

        gameState = "gameover";
        GameStop();

        GetComponent<CapsuleCollider2D>().enabled = false;
        rbody.AddForce(new Vector2(0, 5), ForceMode2D.Impulse);
    }

    //ï¿½Qï¿½[ï¿½ï¿½ï¿½ï¿½~
    void GameStop()
    {
        Rigidbody2D rbody = GetComponent<Rigidbody2D>();
        rbody.velocity = new Vector2(0, 0);
    }
    
}
